version: '3'
services:
   db:
     image: mysql:5.6
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     ports:
       - "27809:3306"
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: prestashop
       MYSQL_USER: user
       MYSQL_PASSWORD: password
     networks:
       - default
   prestashop:
     depends_on:
       - db
     build:
       context: prestashop
     ports:
       - "27709:80"
     restart: always
     volumes:
       - ./datacue-prestashop/:/var/www/html
     environment:
       PS_DEV_MODE: 1
       PS_DOMAIN: home.me
       DB_SERVER: db:3306
       DB_USER: user
       DB_PASSWD: password
       DB_PREFIX: ps_
       DB_NAME: prestashop
     networks:
       - default

